### ISSUE TITLE
User Story 6. High level context

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/smf-prototype#46] opened 2018-04-30 15:07 UTC
As a user I want to see the context of content on the system so that can I understand what it is about and if it is what I am looking for.

**Comment by kareninsignares** [comment] 2018-05-03 13:54
1. About us (EMF)
2. About this learning tool
3. About the Make Fashion Circular project

**Comment by kareninsignares** [comment] 2018-05-29 13:58
Duplicate of #33

**Closed by kareninsignares** 2018-05-29 13:58 UTC
Labels: user-story
